link = "https://github.com/race-of-sloths"
leaderboard_link = "https://github.com/race-of-sloths"
form = "https://github.com/race-of-sloths"
picture_api_link = "https://race-of-sloths.fly.dev/api/badges"

[include_basic_messages]
variables = [
    "pr_author_username",
    "bot_name",
    "link",
    "leaderboard_link",
    "picture_api_link",
]

message = [
    """<details>
<summary> 

### ğŸ‰ This pull request is now a part of the [Race of Sloths]({link})ğŸ‰
Thank you @{pr_author_username} for your contribution!

</summary>
<details>
<summary><strong>More info about the author - @{pr_author_username}</strong></summary>

![sloth_stats]({picture_api_link}/{pr_author_username})

</details> 

<details><summary><strong>What is the Race of Sloths</strong></summary>
<p>

Race of Sloths is a friendly competition where you can participate in challenges and compete with other open-source contributors within your normal workflow

For contributors:

- Tag us inside your pull requests
- Wait for the maintainer to review and score your pull request
- Check out your position in the [Leaderboard]({leaderboard_link})
- Keep weekly and monthly streaks to reach higher positions
- Boast your contributions with a dynamic picture of your [Profile]({link}/profile)

For maintainers:
- Score pull requests that participate in the Race of Sloths
- Engage contributors with fair scoring and fast responses so they keep their streaks
- Promote the Race to the point where the Race starts promoting you
- Grow the community of your contributors

Feel free to check [our website]({link}) for additional details!

</p>
</details> 



<details>
<summary><strong>Bot commands</strong></summary>

- â• **Include a PR:** `@{bot_name} include` to enter the Race with your PR
- ğŸ›‘ **Reject this PR:** `@{bot_name} exclude` to send this PR back to the drawing board.
- â­ **Assign points:** `@{bot_name} score [1/2/3/5/8/13]` to award points based on your assessment.
- ğŸ”• **Pause us:** `@{bot_name} pause` to stop me on your repo.
</details>
</details>
""",
]

[correct_nonzero_scoring_messages]
variables = ["reviewer"]
message = ["""### ğŸŒŸ Score recorded!

@{reviewer}, thank you for scoring this pull request in the Race of Sloths!
"""]

[correct_zero_scoring_messages]
variables = ["pr_author_username"]

message = [
    """### 0âƒ£ï¸ Score recorded! 

@{pr_author_username} Keep your spirits up! Every contribution is a learning opportunity, and your effort is genuinely appreciated. """,
]

[correctable_scoring_messages]
variables = ["score", "corrected_score", "reviewer"]
message = [
    """### ğŸ† Score recorded! 
It looks like @{reviewer} provided a score of {score}, but based on our Fibonacci scoring rules, we've adjusted it to {corrected_score}.
> [!TIP]
We accept only the following Fibonacci numbers [0, 1, 2, 3, 5, 8, 13] for scoring
""",
]

[exclude_messages]
variables = []
message = ["""### ğŸ™ Pull request excluded
Probably, it is not something that the project needs right now
"""]

[pause_messages]
variables = ["bot_name"]
message = [
    """### â¸ï¸ Repository paused 
Scored PRs will be accepted after the merge. No further actions will be taken by the bot until you call `@{bot_name} unpause` command to restart our service
""",
]

[unpause_messages]
variables = []
message = ["""### â–¶ï¸ Repository unpaused! 
Feel free to tag us again to participate in the Race of Sloths!
"""]

[merge_without_score_messages]
variables = []
message = [
    """### ğŸ”„ The PR has been merged.
>[!IMPORTANT]
This pull request is a part of the Race of Sloths and has not been scored yet. Scoring will close in 24 hours! ğŸ•°ï¸""",
]

[final_messages]
variables = ["link", "pr-author-username", "score"]
message = [
    """### âœ… PR is finalized! 
Your contribution is much appreciated with a final score of {score}. Check out the updates in [your profile]({link}/{user})! ğŸŠ""",
]

[stale_messages]
variables = []
message = [
    """### âŒ PR inactive
This PR has been inactive for two weeks. It's now marked as stale. 
>[!TIP]
If you think it's a mistake, you can restart the bot with `include` command to proceed ğŸ”„""",
]

[error_unknown_command_messages]
variables = []
message = ["""### â“Unknown command 
Please check the command and try again"""]

[error_rights_violation_messages]
variables = []
message = ["""### ğŸš« Access denied 
Only maintainers can use this command"""]

[error_late_include_messages]
variables = []
message = ["""### â°ï¸ PR is already merged
It's too late to include us now. Include us before the merge next time!"""]

[error_late_scoring_messages]
variables = []
message = ["""### â°ï¸ Scoring closed
24 hours have already passed since the merge
"""]

[error_pause_paused_messages]
variables = []
message = ["### â¸ï¸ This repository is already on pause"]

[error_unpause_unpaused_messages]
variables = []
message = ["### â–¶ï¸ The repo is already active"]

[error_paused_messages]
variables = ["user", "bot_name"]
message = [
    """### â¸ï¸ This repository is on pause
@{user} please reach out to the maintainer to unpause this repo with `@{bot_name} unpause` command""",
]

[error_selfscore_messages]
variables = []
message = ["""### âŒ Self-scoring is not permitted. 
Let's keep it fair! ğŸ‘"""]

[error_org_not_in_allowed_list_messages]
variables = ["form", "link", "leaderboard_link"]
message = [
    """### ğŸ™ This repository is not a part of the [Race of Sloths]({link})
Please ask the maintainer to [contact us]({form}) to join the race!

<details><summary><strong>What is the Race of Sloths</strong></summary>
<p>

Race of Sloths is a friendly competition where you can participate in challenges and compete with other open-source contributors within your normal workflow

For contributors:

- Tag us inside your pull requests
- Wait for the maintainer to review and score your pull request
- Check out your position in the [Leaderboard]({leaderboard_link})
- Keep weekly and monthly streaks to reach higher positions
- Boast your contributions with a dynamic picture of your [Profile]({link}/profile)

For maintainers:
- Score pull requests that participate in the Race of Sloths
- Engage contributors with fair scoring and fast responses so they keep their streaks
- Promote the Race to the point where the Race starts promoting you
- Grow the community of your contributors

Feel free to check [our website]({link}) for additional details!

</p>
</details> 
""",
]
